import os

class VirtualFile:
  """VirtualFiles are convenience classes for temp files.

  VirtualFile instances are generated by parsing sys.argv to give reference to
  both S3 Objects and there temporary files.

  Args:\n
    \t physical_path (string): The path to the local physical file
    \t s3_key (string): The S3 Key to an object stored on S3
  
  """

  def __init__(self, physical_path, s3_key):
    self.physical_path = physical_path
    self.s3_key = s3_key
    self.base = os.path.basename(s3_key)
    self.dir = os.path.dirname(s3_key)
    self.name, self.ext = os.path.splitext(self.base)
    
    # name_parse = ['2016-10-08-01-01-01', 'pilot01', '6166', 'occupancy']
    name_parse = self.name.split('_')

    if len(name_parse) != 4:
      raise ValueError('s3_key %s could not be parsed.' % s3_key)

    self.timestamp, self.unit, self.room_code, self.file_type = name_parse

  def __str__(self):
    return "%s => %s" % (self.physical_path, self.s3_key)

  def __repr__(self):
    return "%s => %s" % (self.physical_path, self.s3_key)

def parse():
  """Parse sys.argv into a list of {physical_path: string, s3_key: string}

  Args:\n
    \t None

  Returns:\n
    \n List<{physical_path: string, s3_key: string}>

  Raises:\n
    \t ValueError
  """